angular.module('iprpAdminApp', ['ui.utils', 'ui.router', 'ngAnimate', 'ngResource','angularFileUpload','ngFileUpload', 'ngCookies','ui.bootstrap',"ui.bootstrap.tpls", "ng-layer"]);

angular.module('iprpAdminApp').config(function($stateProvider,$httpProvider,datepickerConfig,datepickerPopupConfig,$urlRouterProvider) {
    datepickerConfig.showWeeks = false;
    datepickerPopupConfig.currentText = '今天';
    datepickerPopupConfig.clearText = '清空';
    datepickerPopupConfig.closeText = '关闭';

    var v = window.g_config.timeVersion;

    //登录页面
    $stateProvider.state('login_page',{
        url:'/login_page',
        templateUrl:'scripts/controllers/login/login_page.html?t='+v,
        controller:'LoginPageCtrl',
        css:'styles/css/login.css?t='+v
    })
    .state('main',{
        url:'/main',
        templateUrl:'scripts/controllers/main.html?t='+v,
        controller:'MainCtrl'
    })
    .state('main.left',{
        url:'/left',
        templateUrl:'scripts/controllers/left.html?t='+v,
        controller:'LeftCtrl'
    })
    //主导航：控制台-主页(欢迎页面)
    .state('main.left.home_page',{
        url:'/home_page',
        templateUrl:'scripts/controllers/home_page.html?t='+v,
        controller:'HomePageCtrl'
    })
    //没有操作权限页面
    .state('main.left.error_page',{
        url:'/error_page',
        templateUrl:'scripts/controllers/error_page.html?t='+v,
        controller:'ErrorPageCtrl'
    });

    //主导航：快服
    $stateProvider.state('main.fast_home',{
        url:'/fast_home',
        templateUrl:'scripts/home/fast_home/fast_home.html?t='+v,
        controller:'FastHomeCtrl'
    })
    
    //快服-线索举报
    .state('main.fast_home.clues_report',{
      url:'/clues_report',
      templateUrl:'scripts/controllers/fast/clues_report/clues_report_list.html?t='+v,
      controller:'cluesReportCtrl'
    })
    //快服-线索举报-查看详情
    .state('main.fast_home.clues_report_detail',{
        url:'/clues_report_detail/:consultationId',
        templateUrl:'scripts/controllers/fast/clues_report/clues_report_detail.html?t='+v,
        controller:'cluesReportDetailCtrl'
    })
    //快服-防疫举报
    .state('main.fast_home.epidemic_report',{
      url:'/epidemic_report',
      templateUrl:'scripts/controllers/fast/epidemic_report/epidemic_report_list.html?t='+v,
      controller:'epidemicReportCtrl'
    })
    //快服-防疫举报-查看详情
    .state('main.fast_home.epidemic_report_detail',{
        url:'/epidemic_report_detail/:consultationId',
        templateUrl:'scripts/controllers/fast/epidemic_report/epidemic_report_detail.html?t='+v,
        controller:'epidemicReportDetailCtrl'
    })

    //快服-外贸服务平台
    .state('main.fast_home.foreign_trade_list',{
        url:'/foreign_trade_list',
        templateUrl:'scripts/controllers/fast/foreign_trade/foreign_trade_list.html?t='+v,
        controller:'foreignTradeCtrl'
    })
    //快服-外贸服务平台-详情
    .state('main.fast_home.foreign_trade_detail',{
        url:'/foreign_trade_detail/:id',
        templateUrl:'scripts/controllers/fast/foreign_trade/foreign_trade_detail.html?t='+v,
        controller:'foreignTradeDetailCtrl'
    })
    //快服-oem
    .state('main.fast_home.oem_list',{
        url:'/oem_list',
        templateUrl:'scripts/controllers/fast/oem/oem_list.html?t='+v,
        controller:'oemListCtrl'
    })
    //快服-oem-详情
    .state('main.fast_home.oem_detail',{
        url:'/oem_detail/:id',
        templateUrl:'scripts/controllers/fast/oem/oem_detail.html?t='+v,
        controller:'oemDetailCtrl'
    })
    //快服-存证出证
    .state('main.fast_home.czout_list',{
        url:'/czout_list',
        templateUrl:'scripts/controllers/fast/czout/czout_list.html?t='+v,
        controller:'CzoutListCtrl'
    })
    //快服-存证出证编辑
    .state('main.fast_home.czout_note',{
        url:'/czout_note/:cz_order_sn',
        templateUrl:'scripts/controllers/fast/czout/czout_note.html?t='+v,
        controller:'CzoutNoteCtrl'
    })
    //快服-管家报告
    .state('main.fast_home.keeper_list',{
        url:'/keeper_list',
        templateUrl:'scripts/controllers/fast/reportKeeper/keeper_list.html?t='+v,
        controller:'KeeperListCtrl'
    })
    //快服-管家报告管理
    .state('main.fast_home.keeper_manager',{
        url:'/keeper_manager/:keeper_id',
        templateUrl:'scripts/controllers/fast/reportKeeper/keeper_manager.html?t='+v,
        controller:'KeeperManagerCtrl'
    })
    //快服-管家报告详情
    .state('main.fast_home.keeper_detail',{
        url:'/keeper_detail/:keeper_id',
        templateUrl:'scripts/controllers/fast/reportKeeper/keeper_detail.html?t='+v,
        controller:'KeeperDetailCtrl'
    })
    //快服-电话咨询服务
    .state('main.fast_home.tel_service',{
        url:'/tel_service',
        templateUrl:'scripts/controllers/fast/telService/tel_service_list.html?t='+v,
        controller:'telServiceCtrl'
    })
    //快服-电话咨询服务-查看详情
    .state('main.fast_home.tel_service_detail',{
        url:'/tel_service_detail/:consultationId?isPop',
        templateUrl:'scripts/controllers/fast/telService/tel_service_detail.html?t='+v,
        controller:'telServiceDetailCtrl'
    })
    //快服-服务商意见反馈
    .state('main.fast_home.feedback_service',{
        url:'/feedback_service',
        templateUrl:'scripts/controllers/fast/service_feedback/feedback_service.html?t='+v,
        controller:'feedbackServiceCtrl'
    })
    //快服-服务商意见反馈-详情页
    .state('main.fast_home.feedback_detail',{
        url:'/feedback_detail/:spAdviseId',
        templateUrl:'scripts/controllers/fast/service_feedback/feedback_detail.html?t='+v,
        controller:'feedbackDetailCtrl'
    })
    //快服-服务商入驻申请
    .state('main.fast_home.feedback_apply',{
        url:'/feedback_apply',
        templateUrl:'scripts/controllers/fast/feedback_apply/feedback_apply.html?t='+v,
        controller:'feedbackApplyCtrl'
    })
    //快服-高新企业申报
    .state('main.fast_home.highTechEnterprises',{
        url:'/highTechEnterprises',
        templateUrl:'scripts/controllers/fast/highTechEnterprises/highTechEnterprises.html?t='+v,
        controller:'highTechEnterprisesCtrl'
    })
    //快服-邮寄收件人信息
    .state('main.fast_home.postal',{
        url:'/postal',
        templateUrl:'scripts/controllers/fast/postal/postal.html?t='+v,
        controller:'postalCtrl'
    })
    //快服-商标管家意见反馈
    .state('main.fast_home.feedback',{
        url:'/feedback',
        templateUrl:'scripts/controllers/fast/feedback/feedback.html?t='+v,
        controller:'feedbackCtrl'
    })
    //快服-新合伙人申请
    .state('main.fast_home.partner_app',{
        url:'/partner_app',
        templateUrl:'scripts/controllers/fast/partner_app/partner_app.html?t='+v,
        controller:'partnerAppCtrl'
    })
    //快服-门诊室需求管理
    .state('main.fast_home.outpatient_demand',{
      url:'/outpatient_demand',
      templateUrl:'scripts/controllers/fast/outpatient/demand_list.html?t='+v,
      controller:'FastDemandCtrl'
    })
    //快服-门诊室需求详情 'main/fast_home/demand_detail
    .state('main.fast_home.demand_detail',{
      url:'/demand_detail/:id',
      templateUrl:'scripts/controllers/fast/outpatient/demand_detail.html?t='+v,
      controller:'FastDemandDetail'
    })
    //快服-三年倍增计划 'main/fast_home/demand_detail
    .state('main.fast_home.enterprisesList',{
      url:'/enterprisesList',
      templateUrl:'scripts/controllers/fast/technologyPlan/enterprisesList.html?t='+v,
      controller:'FastEnterprisesListCtrl'
    })
    //快服-三年倍增计划-详情 'main/fast_home/demand_detail
    .state('main.fast_home.enterprisesDetail',{
      url:'/enterprisesDetail/:id',
      templateUrl:'scripts/controllers/fast/technologyPlan/enterprisesDetail.html?t='+v,
      controller:'FastEnterprisesDetailCtrl'
    })
    //快服-IP尽职调查
    .state('main.fast_home.ipSurvey',{
      url:'/ipSurvey',
      templateUrl:'scripts/controllers/fast/technologyPlan/ipSurvey.html?t='+v,
      controller:'IpSurveyCtrl'
    })
    //快服-科技咨询
    .state('main.fast_home.techAdvisory',{
      url:'/techAdvisory',
      templateUrl:'scripts/controllers/fast/technologyPlan/techAdvisory.html?t='+v,
      controller:'TechAdvisoryCtrl'
    })
    //快服-国高数据导入
    .state('main.fast_home.ggImport',{
      url:'/ggImport',
      templateUrl:'scripts/controllers/fast/technologyPlan/ggImport.html?t='+v,
      controller:'GgImportCtrl'
    })
    //快服-省科数据导入
    .state('main.fast_home.skImport',{
      url:'/skImport',
      templateUrl:'scripts/controllers/fast/technologyPlan/skImport.html?t='+v,
      controller:'SkImportCtrl'
    })
    //快服-我要砍价
    .state('main.fast_home.bargain',{
        url:'/bargain',
        templateUrl:'scripts/controllers/fast/bargain/bargain.html?t='+v,
        controller:'bargaineCtrl'
    })
    //快服-我要砍价-详情
    .state('main.fast_home.bargain_detail',{
        url:'/bargain_detail/:id',
        templateUrl:'scripts/controllers/fast/bargain/bargain_detail.html?t='+v,
        controller:'bargainDetailCtrl'
    })
    //快服-商标速卖
    .state('main.fast_home.tm_fast_sell',{
        url:'/tm_fast_sell',
        templateUrl:'scripts/controllers/fast/tm_fast_sell/tm_fast_sell.html?t='+v,
        controller:'tmFastSellCtrl'
    })
    //快服-商标速卖-详情
    .state('main.fast_home.tm_fast_sell_detail',{
        url:'/tm_fast_sell_detail/:id',
        templateUrl:'scripts/controllers/fast/tm_fast_sell/tm_fast_sell_detail.html?t='+v,
        controller:'tmFastSellDetailCtrl'
    })
    //快服-求购好标
    .state('main.fast_home.buy_good_tm',{
        url:'/buy_good_tm',
        templateUrl:'scripts/controllers/fast/buy_good_tm/buy_good_tm.html?t='+v,
        controller:'buyGoodTmCtrl'
    })
    //快服-求购好标-详情
    .state('main.fast_home.buy_good_tm_detail',{
        url:'/buy_good_tm_detail/:orderId',
        templateUrl:'scripts/controllers/fast/buy_good_tm/buy_good_tm_detail.html?t='+v,
        controller:'BuyGoodTmDetailCtrl'
    })
    //合伙人-合伙人入驻申请-合伙人入驻申请
    .state('main.fast_home.partner_application',{
      url:'/partner_application',
      templateUrl:'scripts/controllers/partner/partner_application/partner_application.html?t='+v,
      controller:'PartnerApplicationCtrl'
    })
    //合伙人-合伙人入驻申请-合伙人申请详情
    .state('main.fast_home.partner_application_detail',{
      url:'/partner_application_detail/:partner_id',
      templateUrl:'scripts/controllers/partner/partner_application/partner_application_detail.html?t='+v,
      controller:'PartnerApplicationDetailCtrl'
    })
    //合伙人-合伙人入驻申请-合伙人申请反馈
    .state('main.fast_home.partner_audit',{
      url:'/partner_audit/:partner_id/:type',
      templateUrl:'scripts/controllers/partner/partner_application/partner_audit.html?t='+v,
      controller:'PartnerAuditCtrl'
    })
    //合伙人-合伙人入驻申请-合伙人申请备注
    .state('main.fast_home.partner_application_remarks',{
      url:'/partner_application_remarks/:partner_id',
      templateUrl:'scripts/controllers/partner/partner_application/partner_application_remarks.html?t='+v,
      controller:'PartnerApplicationRemarksCtrl'
    })
    //快服-知识产权维权
    .state('main.fast_home.ip_protect',{
        url:'/ip_protect',
        templateUrl:'scripts/controllers/fast/ipProtect/ip_protect_list.html?t='+v,
        controller:'IpProtectCtrl'
    })
    //快服-知识产权维权-查看详情
    .state('main.fast_home.ip_protect_detail',{
        url:'/ip_protect_detail/:consultationId?isPop',
        templateUrl:'scripts/controllers/fast/ipProtect/ip_protect_detail.html?t='+v,
        controller:'IpProtectDetailCtrl'
    });




    //主导航：订单
    $stateProvider.state('main.trade_home',{
      url:'/trade_home',
      templateUrl:'scripts/home/trade_home/trade_home.html?t='+v,
      controller:'TradeHomeCtrl'
    })
    //敦煌网订单
    .state('main.trade_home.dunhuang_list',{
      url:'/dunhuang_list',
      templateUrl:'scripts/controllers/trade/dunhuang_order/dunhuang_list.html?t='+v,
      controller:'dunhuangCtrl'
    })
    // 敦煌网订单详情
    .state('main.trade_home.dunhuang_detail',{
      url:'/dunhuang_detail/:orderFuwuId',
      templateUrl:'scripts/controllers/trade/dunhuang_order/dunhuang_detail.html?t='+v,
      controller:'dunhuangDetailCtrl'
    })
    //订单-支付单管理
    .state('main.trade_home.order_list',{
      url:'/order_list',
      templateUrl:'scripts/controllers/trade/order/order_list.html?t='+v,
      controller:'OrderListCtrl'
    })
    //订单-支付单管理-查看详情
    .state('main.trade_home.order_detail',{
      url:'/order_detail/:order_id',
      templateUrl:'scripts/controllers/trade/order/order_detail.html?t='+v,
      controller:'OrderDetailCtrl'
    })
    //订单-交易单管理
    .state('main.trade_home.trade_order_list',{
      url:'/trade_order_list',
      templateUrl:'scripts/controllers/trade/order/trade_order_list.html?t='+v,
      controller:'TradeOrderListCtrl'
    })
    //订单-交易单管理-查看详情
    .state('main.trade_home.trade_order_detail',{
      url:'/trade_order_detail/:orderId',
      templateUrl:'scripts/controllers/trade/order/trade_order_detail.html?t='+v,
      controller:'TradeOrderDetailCtrl'
    })
    //订单-合伙人订单管理
    .state('main.trade_home.partner_order_list',{
      url:'/partner_order_list',
      templateUrl:'scripts/controllers/trade/partner_order/order_list.html?t='+v,
      controller:'PartnerOrderListCtrl'
    })
    //订单-合伙人订单-查看详情
    .state('main.trade_home.partner_order_detail', {
      url:'/partner_order_detail/:orderFictitiousSn',
      templateUrl:'scripts/controllers/trade/partner_order/order_detail.html?t='+v,
      controller:'PartnerOrderDetailCtrl'
    })
    //订单-支付单管理-历史订单
    .state('main.trade_home.history_order',{
      url:'/history_order',
      templateUrl:'scripts/controllers/trade/order/history_order.html?t='+v,
      controller:'HistoryOrderCtrl'
    })
    //订单-合伙人服务单
    .state('main.trade_home.partner_bs_order_list',{
      url:'/partner_bs_order_list',
      templateUrl:'scripts/controllers/trade/partner_bs_order/order_list.html?t='+v,
      controller:'PartnerBsOrderListCtrl'
    })
    //订单-合伙人服务单-查看详情
    .state('main.trade_home.partner_bs_order_detail',{
      url:'/partner_bs_order_detail/:order_sn',
      templateUrl:'scripts/controllers/trade/partner_bs_order/order_detail.html?t='+v,
      controller:'PartnerBsOrderDetailCtrl'
    })
    //订单-服务单管理
    .state('main.trade_home.bs_order_list',{
      url:'/bs_order_list',
      templateUrl:'scripts/controllers/trade/bs_order/order_list.html?t='+v,
      controller:'BsOrderListCtrl'
    })
    //订单-服务单管理-查看详情
    .state('main.trade_home.bs_order_detail',{
      url:'/bs_order_detail/:order_sn',
      templateUrl:'scripts/controllers/trade/bs_order/order_detail.html?t='+v,
      controller:'BsOrderDetailCtrl'
    })
    //订单-创新保订单管理
    .state('main.trade_home.cxb_order_list',{
      url:'/cxb_order_list',
      templateUrl:'scripts/controllers/trade/cxb_order/order_list.html?t='+v,
      controller:'CxbOrderListCtrl'
    })
    //订单-创新保订单管理-查看详情
    .state('main.trade_home.cxb_order_detail',{
      url:'/cxb_order_detail/:order_sn',
      templateUrl:'scripts/controllers/trade/cxb_order/order_detail.html?t='+v,
      controller:'CxbOrderDetailCtrl'
    })
    //订单-跨境外贸
    .state('main.trade_home.wm_order_list',{
      url:'/wm_order_list',
      templateUrl:'scripts/controllers/trade/wm_order/order_list.html?t='+v,
      controller:'WmOrderListCtrl'
    })
    //订单-跨境外贸-查看详情
    .state('main.trade_home.wm_order_detail',{
      url:'/wm_order_detail/:order_sn',
      templateUrl:'scripts/controllers/trade/wm_order/order_detail.html?t='+v,
      controller:'WmOrderDetailCtrl'
    })
    //订单-杭州服务贸易
    .state('main.trade_home.hzwm_order_list',{
      url:'/hzwm_order_list',
      params: {
      	'cityId': null
      },
      templateUrl:'scripts/controllers/trade/hzwm_order/order_list.html?t='+v,
      controller:'HzwmOrderListCtrl'
    })
    //订单-杭州服务贸易-查看详情
    .state('main.trade_home.hzwm_order_detail',{
      url:'/hzwm_order_detail/:order_sn',
      templateUrl:'scripts/controllers/trade/hzwm_order/order_detail.html?t='+v,
      controller:'HzwmOrderDetailCtrl'
    })
    //订单-杭州服务贸易-用户列表
    .state('main.trade_home.hzwm_user_list',{
      url:'/hzwm_user_list',
      params: {
      	'areaType': null
      },
      templateUrl:'scripts/controllers/trade/hzwm_order/user_list.html?t='+v,
      controller:'HzwmUserListCtrl'
    })
    //订单-行业惠利（临时放这儿）
    .state('main.trade_home.hyhl_order_list',{
      url:'/hyhl_order_list',
      templateUrl:'scripts/controllers/trade/hyhl_order/order_list.html?t='+v,
      controller:'HyhlOrderListCtrl'
    })
    //订单-渠道工单
    .state('main.trade_home.channel_work_order',{
      url:'/channel_work_order',
      templateUrl:'scripts/controllers/trade/channel_order/work_order_list.html?t='+v,
      controller:'CWOrderListCtrl'
    })
    //订单-渠道工单-查看详情
    .state('main.trade_home.work_order_detail',{
      url:'/work_order_detail/:order_sn',
      templateUrl:'scripts/controllers/trade/channel_order/work_order_detail.html?t='+v,
      controller:'CWOrderDetailCtrl'
    })
    //订单-渠道服务单
    .state('main.trade_home.channel_service_order',{
      url:'/channel_service_order',
      templateUrl:'scripts/controllers/trade/channel_order/service_order_list.html?t='+v,
      controller:'CSOrderListCtrl'
    })
    //订单-渠道服务单-查看详情
    .state('main.trade_home.service_order_detail',{
      url:'/service_order_detail/:order_sn',
      templateUrl:'scripts/controllers/trade/channel_order/service_order_detail.html?t='+v,
      controller:'CSOrderDetailCtrl'
    })
    //订单-渠道支付单
    .state('main.trade_home.channel_order',{
      url:'/channel_order',
      templateUrl:'scripts/controllers/trade/channel_order/order_list.html?t='+v,
      controller:'COrderListCtrl'
    })
    //订单-渠道支付单-查看详情
    .state('main.trade_home.channel_order_detail',{
      url:'/channel_order_detail/:order_sn',
      templateUrl:'scripts/controllers/trade/channel_order/order_detail.html?t='+v,
      controller:'COrderDetailCtrl'
    })
    
    //订单-存证单管理
    .state('main.trade_home.nt_order_list',{
      url:'/nt_order_list',
      templateUrl:'scripts/controllers/trade/nt_order/order_list.html?t='+v,
      controller:'NtOrderListCtrl'
    })
    //订单-存证单管理-查看详情
    .state('main.trade_home.nt_order_detail',{
      url:'/nt_order_detail/:order_sn',
      templateUrl:'scripts/controllers/trade/nt_order/order_detail.html?t='+v,
      controller:'NtOrderDetailCtrl'
    })
    //订单-需求单管理列表
    .state('main.trade_home.demand_list',{
      url:'/demand_list',
      templateUrl:'scripts/controllers/trade/demand_order/order_list.html?t='+v,
      controller:'DemandOrderListCtrl'
    })
    //订单-需求单详情
    .state('main.trade_home.demand_detail',{
      url:'/demand_detail/:id',
      templateUrl:'scripts/controllers/trade/demand_order/order_detail.html?t='+v,
      controller:'DemandOrderDetailCtrl'
    })
    //订单-立体保护订单管理
    .state('main.trade_home.ip_order_list',{
      url:'/ip_order_list',
      templateUrl:'scripts/controllers/trade/ip_order/order_list.html?t='+v,
      controller:'IpOrderListCtrl'
    })
    //订单-立体保护订单管理-查看详情
    .state('main.trade_home.ip_order_detail',{
      url:'/ip_order_detail/:orderSn',
      templateUrl:'scripts/controllers/trade/ip_order/order_detail.html?t='+v,
      controller:'IpOrderDetailCtrl'
    })
    //订单-天猫尼斯推荐订单管理
    .state('main.trade_home.tmall_nice_list',{
      url:'/tmall_nice_list',
      templateUrl:'scripts/controllers/trade/tmall_nice/tmall_nice_list.html?t='+v,
      controller:'TmallNiceListCtrl'
    })

    //订单-退款管理
    .state('main.after_sale_home.refund_list',{
      url:'/refund_list',
      templateUrl:'scripts/controllers/after_sale/refund/refund_list.html?t='+v,
      controller:'RefundListCtrl'
    })
    //订单-退款管理-审核
    .state('main.after_sale_home.refund_check',{
      url:'/refund_check/:refund_id',
      templateUrl:'scripts/controllers/after_sale/refund/refund_check.html?t='+v,
      controller:'RefundCheckCtrl'
    })
    //订单-退款管理-拒绝
    .state('main.after_sale_home.reject_check',{
      url:'/reject_check/:refund_id',
      templateUrl:'scripts/controllers/after_sale/refund/reject_check.html?t='+v,
      controller:'RejectCheckCtrl'
    })
    //订单-退款管理-更新
    .state('main.after_sale_home.update_refund',{
      url:'/update_refund/:refund_id',
      templateUrl:'scripts/controllers/after_sale/refund/update_refund.html?t='+v,
      controller:'UpdateCheckCtrl'
    })
    //订单-退款管理-等待
    .state('main.after_sale_home.wait_refund',{
      url:'/wait_refund/:refund_id',
      templateUrl:'scripts/controllers/after_sale/refund/wait_refund.html?t='+v,
      controller:'WaitRefundCtrl'
    })
    //订单-退款管理-创建
    .state('main.after_sale_home.create_refund',{
      url:'/create_refund/:refund_id',
      templateUrl:'scripts/controllers/after_sale/refund/create_refund.html?t='+v,
      controller:'CreateRefundCtrl'
    })
    //订单-退款管理-添加的退款列表
    .state('main.after_sale_home.refund_add',{
      url:'/refund_add',
      templateUrl:'scripts/controllers/after_sale/refund/refund_add.html?t='+v,
      controller:'RefundAddCtrl'
    })
    // //订单-需求单管理
    // .state('main.after_sale_home.refund_add',{
    //   url:'/refund_add',
    //   templateUrl:'scripts/controllers/after_sale/refund/refund_add.html?t='+v,
    //   controller:'RefundAddCtrl'
    // })
    // //订单-需求单详情
    // .state('main.after_sale_home.refund_add',{
    //   url:'/refund_add',
    //   templateUrl:'scripts/controllers/after_sale/refund/refund_add.html?t='+v,
    //   controller:'RefundAddCtrl'
    // })


    //合伙人-合伙人退款管理
    .state('main.after_sale_home.after_sale_list',{
      url:'/after_sale_list',
      templateUrl:'scripts/controllers/after_sale/partner_after_sale/after_sale_list.html?t='+v,
      controller:'PartnerAfterSaleListCtrl'
    })
    //合伙人-合伙人退款管理-详情页
    .state('main.after_sale_home.after_sale_detail',{
      url:'/after_sale_detail/:id',
      templateUrl:'scripts/controllers/after_sale/partner_after_sale/after_sale_detail.html?t='+v,
      controller:'PartnerAfterSaleDetailCtrl'
    }) ;

    /**
     * 服务商信息
     */
    //主导航：服务商合并至商家部分
    $stateProvider.state('main.service_home',{
        url:'/service_home',
        templateUrl:'scripts/home/service_home/service_home.html?t='+v,
        controller:'ServicerHomeCtrl'
    });

    //商家
    $stateProvider.state('main.merchant_home',{
      url:'/merchant_home',
      templateUrl:'scripts/home/merchant_home/merchant_home.html?t='+v,
      controller:'MerchantHomeCtrl'
    })
    .state('main.merchant_home.merchant_list',{
      url:'/merchantList',
      templateUrl:'scripts/controllers/merchant/merchant_list.html?t='+v,
      controller:'MerchantListCtrl'
    })
    .state('main.merchant_home.merchant_edit',{
      url:'/merchantEdit/:spId/:spCode',
      templateUrl:'scripts/controllers/merchant/merchant_edit.html?t='+v,
      controller:'MerchantEditCtrl'
    })
    .state('main.merchant_home.merchant_detail',{
      url:'/merchantDetail/:spId',
      templateUrl:'scripts/controllers/merchant/merchant_detail.html?t='+v,
      controller:'MerchantDetailCtrl'
    })
    
    //商家入驻-入驻申请
    .state('main.merchant_home.seller_application',{
      url:'/seller_application',
      templateUrl:'scripts/controllers/service/application_for_admission/seller_application.html?t=' + v,
      controller:'SellerApplicationCtrl'
    })
    //商家入驻-入驻申请详情
    .state('main.merchant_home.seller_application_detail',{
      url:'/seller_application_detail/:seller_id',
      templateUrl:'scripts/controllers/service/application_for_admission/seller_application_detail.html?t=' + v,
      controller:'SellerApplicationDetailCtrl'
    })
    //商家入驻-入驻申请备注
    .state('main.merchant_home.seller_application_remarks',{
      url:'/seller_application_remarks/:seller_id/:id',
      templateUrl:'scripts/controllers/service/application_for_admission/seller_application_remarks.html?t=' + v,
      controller:'SellerApplicationRemarksCtrl'
    })

    //商家入驻-入驻审核
    .state('main.merchant_home.seller_audit',{
      url:'/seller_audit/:seller_id/:type',
      templateUrl:'scripts/controllers/service/application_for_admission/seller_audit.html?t=' + v,
      controller:'SellerAuditCtrl'
    })

    //
    //服务商-服务商管理
    .state('main.merchant_home.servicer_list',{
        url:'/servicer_list',
        templateUrl:'scripts/controllers/service/servicer_list.html?t='+v,
        controller:'ServicerListCtrl'
    })
    //服务商-服务商统计
    .state('main.merchant_home.servicer_statistics',{
        url:'/servicer_statistics',
        templateUrl:'scripts/controllers/service/servicer_statistics.html?t='+v,
        controller:'ServicerStatisticsCtrl'
    })
    //服务商-服务商管理-添加服务商
    .state('main.merchant_home.add_servicer',{
        url:'/add_servicer',
        templateUrl:'scripts/controllers/service/add_servicer.html?t='+v,
        controller:'AddServicerCtrl'
    })
    //服务商-服务商管理-服务商查看
    .state('main.merchant_home.servicer_detail',{
        url:'/servicer_detail/:sp_id',
        templateUrl:'scripts/controllers/service/servicer_detail.html?t='+v,
        controller:'ServicerDetailCtrl'
    })
    //服务商-服务商管理-服务商编辑
    .state('main.merchant_home.edit_servicer',{
        url:'/edit_servicer/:sp_id',
        templateUrl:'scripts/controllers/service/edit_servicer.html?t='+v,
        controller:'EditServicerCtrl'
    })
    //服务商-服务商管理-服务商管理
    .state('main.merchant_home.servicer_manage',{
        url:'/servicer_manage/:sp_id',
        templateUrl:'scripts/controllers/service/servicer_manage.html?t='+v,
        controller:'ServicerManageCtrl'
    })
    //服务商-失信服务商
    .state('main.merchant_home.bad_servicer_list',{
        url:'/bad_servicer_list',
        templateUrl:'scripts/controllers/service/bad_servicer_list.html?t='+v,
        controller:'BadServicerListCtrl'
    })
    //服务商-失信服务商-编辑
    .state('main.merchant_home.edit_badServicer',{
        url:'/edit_badServicer/:sp_id',
        templateUrl:'scripts/controllers/service/edit_badServicer.html?t='+v,
        controller:'EditBadServicerCtrl'
    })
    //服务商-失信服务商-添加
    .state('main.merchant_home.add_badServicer',{
        url:'/add_badServicer',
        templateUrl:'scripts/controllers/service/add_badServicer.html?t='+v,
        controller:'AddBadServicerCtrl'
    })
    //服务商-失信服务商-添加失信服务商管理
    .state('main.merchant_home.add_badServiceManage',{
        url:'/add_badServiceManage/:sp_id',
        templateUrl:'scripts/controllers/service/add_badServiceManage.html?t='+v,
        controller:'AddBadServicerManageCtrl'
    })
    //服务商-失信服务商-重置密码
    .state('main.merchant_home.reset_pwd',{
        url:'/reset_pwd/:sp_id',
        templateUrl:'scripts/controllers/service/reset_pwd.html?t='+v,
        controller:'ServicerResetPwdCtrl'
    })
    //服务商-结算模板管理-结算模板列表
    .state('main.merchant_home.bill_tpl_list',{
      url:'/bill_tpl_list',
      templateUrl:'scripts/controllers/service/bill_manage/bill_tpl_list.html?t='+v,
      controller:'BillTplListCtrl'
    })
    //服务商-结算模板管理-添加结算模板
    .state('main.merchant_home.add_tpl',{
      url:'/add_tpl',
      templateUrl:'scripts/controllers/service/bill_manage/add_tpl.html?t='+v,
      controller:'AddTplCtrl'
    })
    //服务商-结算模板管理-添加结算模板
    .state('main.merchant_home.add_bill_tpl_deploy',{
      url:'/add_bill_tpl_deploy/:bill_template_id',
      templateUrl:'scripts/controllers/service/bill_manage/add_bill_tpl_deploy.html?t='+v,
      controller:'AddBillTplDeployCtrl'
    })
    //服务商-结算模板管理-编辑结算模板
    .state('main.merchant_home.edit_bill_tpl_deploy',{
      url:'/edit_bill_tpl_deploy/:bill_template_id',
      templateUrl:'scripts/controllers/service/bill_manage/edit_bill_tpl_deploy.html?t='+v,
      controller:'EditBillTplDeployCtrl'
    })
    //服务商-商家标签管理-标签列表
    .state('main.merchant_home.label_tpl_list',{
      url:'/label_tpl_list',
      templateUrl:'scripts/controllers/service/label_manage/label_tpl_list.html?t=' + v,
      controller:'LabelTplListCtrl'
    })
    //服务商-商家标签管理-标签编辑
    .state('main.merchant_home.label_tpl_edit',{
      url:'/label_tpl_edit/:label_id',
      templateUrl:'scripts/controllers/service/label_manage/label_tpl_edit.html?t=' + v,
      controller:'LabelTplEditCtrl'
    })
    //服务商-商家标签管理-标签添加
    .state('main.merchant_home.label_tpl_add',{
      url:'/label_tpl_add',
      templateUrl:'scripts/controllers/service/label_manage/label_tpl_add.html?t=' + v,
      controller:'LabelTplAddCtrl'
    })

    //服务商-服务商结算-列表
    .state('main.merchant_home.sp_bill',{
      url:'/sp_bill',
      templateUrl:'scripts/controllers/service/sp_bill/sp_bill.html?t='+v,
      controller:'SpBillCtrl'
    })
    //服务商-服务商结算-账单详情
    .state('main.merchant_home.bill_detail',{
      url:'/bill_detail/:bill_id',
      templateUrl:'scripts/controllers/service/sp_bill/bill_detail.html?t='+v,
      controller:'BillDetailCtrl'
    })
    //服务商-服务商结算-结算单列表
    .state('main.merchant_home.statement',{
      url:'/statement/:sp_id',
      templateUrl:'scripts/controllers/service/sp_bill/statement.html?t='+v,
      controller:'StatementCtrl'
    })
    //服务商-服务商资金账户-资金账户列表
    .state('main.merchant_home.capital_account',{
      url:'/capital_account',
      templateUrl:'scripts/controllers/service/sp_capital_account/capital_account.html?t='+v,
      controller:'CapitalAccountCtrl'
    })
    //服务商-服务商资金账户-账户明细列表
    .state('main.merchant_home.account_detail',{
      url:'/account_detail/:sp_id',
      templateUrl:'scripts/controllers/service/sp_capital_account/account_detail.html?t='+v,
      controller:'AccountDetailCtrl'
    })
    //服务商-商家管理-服务管理
    .state('main.merchant_home.service_manage',{
      url:'/service_manage/:b_id',
      templateUrl:'scripts/controllers/service/business_manage/service_manage.html?t='+v,
      controller:'serviceManageCtrl'
    });

    //主导航: 管家
    $stateProvider.state('main.master_home',{
      url:'/master_home',
      templateUrl:'scripts/home/master_home/master_home.html?t='+v,
      controller:'MasterHomeCtrl'
    })
    //管家-存证业务
    .state('main.master_home.cz_list',{
      url:'/cz_list',
      templateUrl:'scripts/controllers/master/cunZ/cz_list.html?t='+v,
      controller:'MasterCzCtrl'
    })
    //管家-存证业务-查看
    .state('main.master_home.cz_detail',{
      url:'/cz_detail/:order_sn',
      templateUrl:'scripts/controllers/master/cunZ/cz_detail.html?t='+v,
      controller:'MasterCzDetailCtrl'
    });

    //主导航：售后
    $stateProvider.state('main.after_sale_home',{
    url:'/after_sale_home',
    templateUrl:'scripts/home/after_sale_home/after_sale_home.html?t='+v,
    controller:'AfterSaleCtrl'
  });

  /**
   * 用户管理
   */
    //主导航：会员
  $stateProvider.state('main.user_home',{
      url:'/user_home',
      templateUrl:'scripts/home/user_home/user_home.html?t='+v,
      controller:'UserHomeCtrl'
    })
    //企业主体认证审核-列表
    .state('main.user_home.company_audit_list',{
      url:'/company_audit_list',
      templateUrl:'scripts/controllers/user_manage/companyaudit/companyauditlist.html?t='+v,
      controller:'CompanyAuditListCtrl'
    })
    .state('main.user_home.company_audit_detail',{
      url:'/company_audit_detail/:applySubjectId',
      templateUrl:'scripts/controllers/user_manage/companyaudit/companyauditdetail.html?t='+v,
      controller:'CompanyAuditDetailCtrl'
    })
    //会员-会员列表（老的）
    .state('main.user_home.user_list',{
      url:'/user_list',
      templateUrl:'scripts/controllers/user_manage/user/user_list.html?t='+v,
      controller:'UserManageListCtrl'
    })
    //会员-会员列表（新的）
    .state('main.user_home.user_list_520',{
      url:'/user_list_520',
      templateUrl:'scripts/controllers/user_manage/user_520/user_list.html?t='+v,
      controller:'UserManageList520Ctrl'
    })
    //会员-会员列表-查看详情
    .state('main.user_home.user_detail_520',{
      url:'/user_detail_520/:member_id',
      templateUrl:'scripts/controllers/user_manage/user_520/user_detail.html?t='+v,
      controller:'UserDetail520Ctrl'
    })
    //会员-集团会员申请-编辑
    .state('main.user_home.edit_user',{
      url:'/edit_user/:member_id',
      templateUrl:'scripts/controllers/user_manage/user/edit_user.html?t='+v,
      controller:'EditUserCtrl'
    })
    //会员-集团会员申请-申请列表
    .state('main.user_home.apply_user_list',{
      url:'/apply_user_list',
      templateUrl:'scripts/controllers/user_manage/apply_user/apply_user_list.html?t='+v,
      controller:'ApplyUserListCtrl'
    })

    /*.state('main.user_home.apply_user_list_test',{
     url:'/apply_user_list_test',
     templateUrl:'scripts/controllers/user_manage/apply_user/apply_user_list_test.html?t='+v,
     controller:'ApplyUserListTestCtrl'
     })*/

    //会员-用户黑名单
    .state('main.user_home.user_black_list',{
      url:'/user_black_list',
      templateUrl:'scripts/controllers/user_manage/user_black/user_black_list.html?t='+v,
      controller:'UserManageListBlackCtrl'
    })
    .state('main.user_home.service_record',{
      url:'/service_record/:member_id',
      templateUrl:'scripts/controllers/user_manage/user/service_record.html?t='+v,
      controller:'ServiceRecordCtrl'
    })
    //会员-集团会员申请-申请列表-查看
    .state('main.user_home.apply_user_detail',{
      url:'/apply_user_detail/:member_id',
      templateUrl:'scripts/controllers/user_manage/apply_user/apply_user_detail.html?t='+v,
      controller:'ApplyUserDetailCtrl'
    })
    //会员-集团会员申请-会员列表-查看
    .state('main.user_home.user_detail',{
      url:'/user_detail/:member_id',
      templateUrl:'scripts/controllers/user_manage/user/user_detail.html?t='+v,
      controller:'UserDetailCtrl'
    })
    //会员-指定服务商
    .state('main.user_home.assignService_list',{
      url:'/assignService_list',
      templateUrl:'scripts/controllers/user_manage/assignService/assignService_list.html?t='+v,
      controller:'AssignServiceListCtrl'
    })
    //会员-指定服务商-编辑
    .state('main.user_home.edit_assignService',{
      url:'/edit_assignService/:designation_id',
      templateUrl:'scripts/controllers/user_manage/assignService//edit_assignService.html?t='+v,
      controller:'EditAssignServiceCtrl'
    })
    //会员-指定服务商-添加
    .state('main.user_home.add_assignService',{
      url:'/add_assignService',
      templateUrl:'scripts/controllers/user_manage/assignService//add_assignService.html?t='+v,
      controller:'AddAssignServiceCtrl'
    })
    //会员-指定服务商-指定服务商
    .state('main.user_home.assignService',{
      url:'/assignService/:designation_id',
      templateUrl:'scripts/controllers/user_manage/assignService//assignService.html?t='+v,
      controller:'AssignServiceCtrl'
    });
  /**
   * 业务
   */
    //主导航：商品
    $stateProvider.state('main.business_home',{
      url:'/business_home',
      templateUrl:'scripts/home/business_home/business_home.html?t='+v,
      controller:'BusinessHomeCtrl'
    })
    //商品-服务管理
    .state('main.business_home.business_list',{
      url:'/business_list',
      templateUrl:'scripts/controllers/business/business_list.html?t='+v,
      controller:'BusinessListCtrl'
    })
    //商品-服务管理-添加服务
    .state('main.business_home.add_business',{
      url:'/add_business',
      templateUrl:'scripts/controllers/business/add_business.html?t='+v,
      controller:'AddBusinessCtrl'
    })
    //商品-服务管理-添加服务配置
    .state('main.business_home.add_business_feedback',{
      url:'/add_business_feedback/:bs_id',
      templateUrl:'scripts/controllers/business/add_business_feedback.html?t='+v,
      controller:'AddBusinessFeedBackCtrl'
    })
    //商品-服务管理-编辑服务配置
    .state('main.business_home.edit_business_feedback',{
      url:'/edit_business_feedback/:bs_id',
      templateUrl:'scripts/controllers/business/edit_business_feedback.html?t='+v,
      controller:'EditBusinessFeedBackCtrl'
    })
    //商品-服务分类-服务分类列表
    .state('main.business_home.business_class_list',{
      url:'/business_class_list',
      templateUrl:'scripts/controllers/business/business_class_list.html?t='+v,
      controller:'BusinessClassListCtrl'
    })
    //商品-商城服务类目-列表
    .state('main.business_home.mall_service_class',{
      url:'/mall_service_class',
      templateUrl:'scripts/controllers/business/mallService/mall_service_class.html?t='+v,
      controller:'mallServiceClassCtrl'
    })
    //商品-商城服务类目-添加
    .state('main.business_home.add_mall_service_class',{
      url:'/add_mall_service_class',
      templateUrl:'scripts/controllers/business/add_mall_service_class.html?t='+v,
      controller:'addMallServiceClassCtrl'
    })
    //商品-商城服务类目-编辑
    .state('main.business_home.edit_mall_service_class',{
      url:'/edit_mall_service_class/:bs_class_id',
      templateUrl:'scripts/controllers/business/edit_mall_service_class.html?t='+v,
      controller:'EditMallServiceCtrl'
    })
    //商品-服务分类-添加服务分类
    .state('main.business_home.add_business_class',{
      url:'/add_business_class',
      templateUrl:'scripts/controllers/business/add_business_class.html?t='+v,
      controller:'AddBusinessClassCtrl'
    })
    //商品-服务分类-编辑服务分类
    .state('main.business_home.edit_business_class',{
      url:'/edit_business_class/:bs_class_id',
      templateUrl:'scripts/controllers/business/edit_business_class.html?t='+v,
      controller:'EditBusinessClassCtrl'
    })
    //商品-拾贝商品管理
    .state('main.business_home.product_list',{
      url:'/product_list',
      templateUrl:'scripts/controllers/business/product_list.html?t='+v,
      controller:'ProductListCtrl'
    })
    //商品-拾贝商品管理-商品详情
    .state('main.business_home.product_detail',{
      url:'/product_detail/:productPriceId',
      templateUrl:'scripts/controllers/business/product_detail.html?t='+v,
      controller:'ProductDetailCtrl'
    })
    //商品-拾贝商品管理-添加商品
    .state('main.business_home.add_product',{
      url:'/add_product',
      templateUrl:'scripts/controllers/business/add_product.html?t='+v,
      controller:'AddProductCtrl'
    })
    //商品-拾贝商品管理-修改商品
    .state('main.business_home.edit_product',{
      url:'/edit_product',
      templateUrl:'scripts/controllers/business/edit_product.html?t='+v,
      controller:'EditProductCtrl'
    })
    //商品-拾贝商品管理-修改
    .state('main.business_home.edit_good_detail',{
      url:'/edit_good_detail/:productPriceId',
      templateUrl:'scripts/controllers/business/edit_good_detail.html?t='+v,
      controller:'EditGoodDetailCtrl'
    })
    //商品-商标管理
    .state('main.business_home.tm_manage',{
      url:'/tm_manage',
      templateUrl:'scripts/controllers/business/tm_manage.html?t='+v,
      controller:'BusinessTmManageCtrl'
    })
    //商品-商标管理-详情
    .state('main.business_home.tm_manage_detail',{
      url:'/tm_manage_detail/:tmiD',
      templateUrl:'scripts/controllers/business/tm_manage_detail.html?t='+v,
      controller:'BusinessTmManageDetailCtrl'
    })
    //商品-店铺服务管理-列表
    .state('main.business_home.shop_service_manage',{
      url:'/shop_service_manage',
      templateUrl:'scripts/controllers/business/shop_service_manage.html?t='+v,
      controller:'BusinessShopServiceManageCtrl'
    })
    //商品-店铺服务管理-详情
    .state('main.business_home.shop_service_detail',{
      url:'/shop_service_detail/:id',
      templateUrl:'scripts/controllers/business/shop_service_detail.html?t='+v,
      controller:'BusinessShopServiceDetailCtrl'
    })
    //商品-合伙人商品-列表
    .state('main.business_home.coupon_list',{
      url:'/coupon_list',
      templateUrl:'scripts/controllers/business/coupon/coupon_list.html?t='+v,
      controller:'couponListCtrl'
    })
    //商品-合伙人商品-列表
    .state('main.business_home.coupon_redact',{
      url:'/coupon_redact/:id',
      templateUrl:'scripts/controllers/business/coupon/coupon_redact.html?t='+v,
      controller:'couponRedactCtrl'
    });

    //营销
    $stateProvider.state('main.market_home',{
      url:'/market_home',
      templateUrl:'scripts/home/market_home/market_home.html?t='+v,
      controller:'MarketHomeCtrl'
    })
    .state('main.market_home.rechargeList',{
      url:'/rechargeList',
      templateUrl:'scripts/controllers/market/809/rechargeList.html?t='+v,
      controller:'MarketRechargeListCtrl'
    })
    .state('main.market_home.prizeList',{
      url:'/prizeList',
      templateUrl:'scripts/controllers/market/809/prizeList.html?t='+v,
      controller:'MarketPrizeListCtrl'
    })
    .state('main.market_home.activeSet',{
      url:'/activeSet',
      templateUrl:'scripts/controllers/market/809/activeSet.html?t='+v,
      controller:'MarketActiveSetCtrl'
    })
    .state('main.market_home.platform',{
      url:'/platform',
      templateUrl:'scripts/controllers/market/platform/platform_list.html?t='+v,
      controller:'PlatformListCtrl'
    })
    .state('main.market_home.platformAdd',{//新增运营位
      url:'/platformAdd',
      templateUrl:'scripts/controllers/market/platform/platform_add.html?t='+v,
      controller:'PlatformAddCtrl'
    })
    .state('main.market_home.platformEdit',{//编辑运营位
      url:'/platformEdit/:id',
      templateUrl:'scripts/controllers/market/platform/platform_edit.html?t='+v,
      controller:'PlatformEditCtrl'
    })
    .state('main.market_home.operation',{
      url:'/operation',
      templateUrl:'scripts/controllers/market/operation/operation_list.html?t='+v,
      controller:'OperationListCtrl'
    })
    .state('main.market_home.coupon',{//拾贝券管理
      url:'/coupon',
      templateUrl:'scripts/controllers/market/coupon/coupon_list.html?t='+v,
      controller:'CouponListCtrl'
    })
    .state('main.market_home.coupon_record',{//拾贝券领取
      url:'/coupon_record',
      templateUrl:'scripts/controllers/market/coupon/coupon_record_list.html?t='+v,
      controller:'CouponRecordListCtrl'
    })
    .state('main.market_home.coupon_add',{//添加优惠券
      url:'/coupon_add',
      templateUrl:'scripts/controllers/market/coupon/coupon_add.html?t='+v,
      controller:'CouponAddCtrl'
    })
    .state('main.market_home.coupon_look',{//查看优惠券
      url:'/coupon_look/:couponId',
      templateUrl:'scripts/controllers/market/coupon/coupon_look.html?t='+v,
      controller:'CouponLookCtrl'
    });

    //内容
    $stateProvider.state('main.cms_home_list',{
      url:'/cms_home_list',
      templateUrl:'scripts/home/cms_home/cms_home.html?t='+v,
      controller:'CmsHomeCtrl'
    })
    .state('main.cms_home_list.cmsList',{//商品列表
      url:'/cmsList',
      templateUrl:'scripts/controllers/cms/cms_list.html?t='+v,
      controller:'CmsListCtrl'
    })
    .state('main.cms_home_list.cmsDetail',{//商品详情
      url:'/cmsDetail/:id',
      templateUrl:'scripts/controllers/cms/cms_detail.html?t='+v,
      controller:'CmsDetailCtrl'
    })
    .state('main.cms_home_list.cmsShopList',{//店铺列表
      url:'/cmsShopList',
      templateUrl:'scripts/controllers/cms/cms_shop_list.html?t='+v,
      controller:'CmsShopListCtrl'
    })
    .state('main.cms_home_list.cmsShopDetail',{//店铺详情
      url:'/cmsShopDetail/:id',
      templateUrl:'scripts/controllers/cms/cms_shop_detail.html?t='+v,
      controller:'CmsShopDetailCtrl'
    })
    .state('main.cms_home_list.cmsTag',{//评价标签
      url:'/cmsTag',
      templateUrl:'scripts/controllers/cms/cms_tag.html?t='+v,
      controller:'CmsTagCtrl'
    })
    .state('main.cms_home_list.banner',{//拾贝宝banner
      url:'/banner',
      templateUrl:'scripts/controllers/cms/sbbBanner/sbbBanner.html?t='+v,
      controller:'SbbBannerCtrl'
    })
    .state('main.cms_home_list.addBanner',{//添加banner
      url:'/addBanner/:id',
      templateUrl:'scripts/controllers/cms/sbbBanner/addBanner.html?t='+v,
      controller:'AddBannerCtrl'
    })
    .state('main.cms_home_list.notice',{//拾贝宝公告
      url:'/notice',
      templateUrl:'scripts/controllers/cms/sbbNotice/sbbNoticeList.html?t='+v,
      controller:'SbbNoticeListCtrl'
    })
    .state('main.cms_home_list.addNotice',{//添加公告
      url:'/addNotice/:id',
      templateUrl:'scripts/controllers/cms/sbbNotice/addNotice.html?t='+v,
      controller:'AddNoticeCtrl'
    })

    .state('main.cms_home_list.IPTNotice',{//珍珠公告
      url:'/IPTNotice',
      templateUrl:'scripts/controllers/cms/IPTNotice/sbbNoticeList.html?t='+v,
      controller:'IPTNoticeListCtrl'
    })
    .state('main.cms_home_list.addIPTNotice',{//添加珍珠公告
      url:'/addIPTNotice/:id',
      templateUrl:'scripts/controllers/cms/IPTNotice/addNotice.html?t='+v,
      controller:'AddIPTNoticeCtrl'
    })
    .state('main.cms_home_list.story',{//合伙人故事
      url:'/story',
      templateUrl:'scripts/controllers/cms/parterStory/storyList.html?t='+v,
      controller:'StoryListCtrl'
    })
    .state('main.cms_home_list.addStory',{//添加故事
      url:'/addStory/:id',
      templateUrl:'scripts/controllers/cms/parterStory/addStory.html?t='+v,
      controller:'AddStoryCtrl'
    })
    .state('main.cms_home_list.tech',{//拾贝宝教程
      url:'/tech',
      templateUrl:'scripts/controllers/cms/sbbTech/techList.html?t='+v,
      controller:'TechListCtrl'
    })
    .state('main.cms_home_list.addTech',{//添加教程
      url:'/addTech/:id',
      templateUrl:'scripts/controllers/cms/sbbTech/addTech.html?t='+v,
      controller:'AddTechCtrl'
    }).state('main.cms_home_list.ruleList',{//合伙人规则
      url:'/ruleList',
      templateUrl:'scripts/controllers/cms/sbbRule/sbbRule.html?t='+v,
      controller:'SbbRuleCtrl'
    }).state('main.cms_home_list.addRule',{//添加规则
      url:'/addRule/:id',
      templateUrl:'scripts/controllers/cms/sbbRule/addRule.html?t='+v,
      controller:'AddRuleCtrl'
    });


    //主导航：财务
    $stateProvider.state('main.finance_home',{
      url:'/finance_home',
      templateUrl:'scripts/home/finance_home/finance_home.html?t='+v,
      controller:'BillHomeCtrl'
    })

    //财务-发票管理-国内商标线上
    .state('main.finance_home.trademark_online',{
      url:'/trademark_online',
      templateUrl:'scripts/controllers/finance/trademark/list.html?t='+v,
      controller:'trademarkOnlineCtrl'
    })
    //财务-发票管理-国内商标云表
    .state('main.finance_home.trademark_table',{
      url:'/trademark_table',
      templateUrl:'scripts/controllers/finance/trademark/tablist.html?t='+v,
      controller:'trademarkTableCtrl'
    })
    //财务-发票管理-国际商标
    .state('main.finance_home.trademark_inter',{
      url:'/trademark_inter',
      templateUrl:'scripts/controllers/finance/trademark/interlist.html?t='+v,
      controller:'trademarkInterCtrl'
    })
    //财务-发票管理-商标其他业务
    .state('main.finance_home.trademark_other',{
      url:'/trademark_other',
      templateUrl:'scripts/controllers/finance/trademark/otherlist.html?t='+v,
      controller:'trademarkOtherCtrl'
    })
    //财务-发票管理-版权
    .state('main.finance_home.copyright',{
      url:'/copyright',
      templateUrl:'scripts/controllers/finance/trademark/copyright.html?t='+v,
      controller:'copyrightCtrl'
    })
    //财务-发票管理-科技项目
    .state('main.finance_home.techlistyb',{
      url:'/techlistyb',
      templateUrl:'scripts/controllers/finance/trademark/techlist.html?t='+v,
      controller:'techlistybCtrl'
    })
    //财务-发票管理-专利许可
    .state('main.finance_home.zlxklist',{
      url:'/zlxklist',
      templateUrl:'scripts/controllers/finance/trademark/zlxklist.html?t='+v,
      controller:'zlxklistCtrl'
    })
    //财务-发票管理-遗留案件
    .state('main.finance_home.ylzllist',{
      url:'/ylzllist',
      templateUrl:'scripts/controllers/finance/trademark/ylzllist.html?t='+v,
      controller:'ylzllistCtrl'
    })

    //财务-发票管理-未开列表
    .state('main.finance_home.unopen_list',{
      url:'/unopen_list',
      templateUrl:'scripts/controllers/finance/invoice/unopen_list.html?t='+v,
      controller:'UnOpenListCtrl'
    })
    //财务-发票管理-已开列表
    .state('main.finance_home.open_list',{
      url:'/open_list',
      templateUrl:'scripts/controllers/finance/invoice/open_list.html?t='+v,
      controller:'OpenListCtrl'
    })
    //财务-发票管理-查看
    .state('main.finance_home.backfill_invoice',{
      url:'/backfill_invoice/:invoice_id',
      templateUrl:'scripts/controllers/finance/invoice/backfill_invoice.html?t='+v,
      controller:'BackFillInvoiceCtrl'
    })
    //财务-发票管理-物流
    .state('main.finance_home.backfill_express',{
      url:'/backfill_express/:invoice_id',
      templateUrl:'scripts/controllers/finance/invoice/backfill_express.html?t='+v,
      controller:'BackFillExpressCtrl'
    })
    //财务-发票管理-查看
    .state('main.finance_home.open_invoice_detail',{
      url:'/open_invoice_detail/:invoice_id',
      templateUrl:'scripts/controllers/finance/invoice/open_invoice_detail.html?t='+v,
      controller:'OpenInvoiceDetailCtrl'
    })
    //财务-红冲发票管理-查看
    .state('main.finance_home.red_open_detail',{
      url:'/red_open_detail/:invoice_id',
      templateUrl:'scripts/controllers/finance/red_invoice/red_open_detail.html?t='+v,
      controller:'RedOpenDetailCtrl'
    })
    //财务-红冲发票管理-查看
    .state('main.finance_home.original_invoice_detail',{
      url:'/original_invoice_detail/:invoice_id',
      templateUrl:'scripts/controllers/finance/red_invoice/original_invoice_detail.html?t='+v,
      controller:'OriginalInvoiceDetailCtrl'
    })
    //财务-红冲发票管理-查看原始发票
    .state('main.finance_home.red_check_list',{
      url:'/red_check_list',
      templateUrl:'scripts/controllers/finance/red_invoice/red_check_list.html?t='+v,
      controller:'RedCheckListCtrl'
    })
    //财务-红冲发票管理-查看原始发票
    .state('main.finance_home.red_unopen_list',{
      url:'/red_unopen_list',
      templateUrl:'scripts/controllers/finance/red_invoice/red_unopen_list.html?t='+v,
      controller:'RedUnOpenListCtrl'
    })
    //财务-红冲发票管理-未开列表
    .state('main.finance_home.red_open_list',{
      url:'/red_open_list',
      templateUrl:'scripts/controllers/finance/red_invoice/red_open_list.html?t='+v,
      controller:'RedOpenListCtrl'
    })
    //财务-红冲发票管理-审核
    .state('main.finance_home.red_check',{
      url:'/red_check/:invoice_id',
      templateUrl:'scripts/controllers/finance/red_invoice/red_check.html?t='+v,
      controller:'RedCheckCtrl'
    })
    //财务-红冲发票管理-处理
    .state('main.finance_home.red_backfill',{
      url:'/red_backfill/:invoice_id',
      templateUrl:'scripts/controllers/finance/red_invoice/red_backfill.html?t='+v,
      controller:'RedBackFillCtrl'
    })
    //财务-创新保对账数据
    .state('main.finance_home.cxb',{
      url:'/cxb',
      templateUrl:'scripts/controllers/finance/cxb/cxb.html?t='+v,
      controller:'CxbCtrl'
    })
    //财务-浙商智能对账数据
    .state('main.finance_home.zs_ai',{
      url:'/zs_ai',
      templateUrl:'scripts/controllers/finance/zs_ai/zs_ai.html?t='+v,
      controller:'zsAiCtrl'
    })
    //财务-浙商智能对账数据-单笔订单查询
    .state('main.finance_home.zs_single',{
      url:'/zs_single',
      templateUrl:'scripts/controllers/finance/zs_ai/zs_single.html?t='+v,
      controller:'zsSingleCtrl'
    });

    /**
     * 渠道商信息
     */
    //主导航：渠道
    $stateProvider.state('main.channel_home',{
        url:'/channel_home',
        templateUrl:'scripts/home/channel_home/channel_home.html?t='+v,
        controller:'ChannelHomeCtrl'
    })
    //渠道-渠道商管理-列表
    .state('main.channel_home.channel_list',{
        url:'/channel_list',
        templateUrl:'scripts/controllers/channel/channel_list.html?t='+v,
        controller:'ChannelListCtrl'
    })
    //渠道-渠道商管理-添加
    .state('main.channel_home.add_channel',{
        url:'/add_channel',
        templateUrl:'scripts/controllers/channel/add_channel.html?t='+v,
        controller:'AddChannelCtrl'
    })
    //渠道-渠道商管理-编辑
    .state('main.channel_home.edit_channel',{
        url:'/edit_channel/:channel_id',
        templateUrl:'scripts/controllers/channel/edit_channel.html?t='+v,
        controller:'EditChannelCtrl'
    })
    //渠道-渠道商管理-指定服务商
    .state('main.channel_home.assign_servicer',{
        url:'/assign_servicer/:channel_id',
        templateUrl:'scripts/controllers/channel/assign_servicer.html?t='+v,
        controller:'AssignServicerCtrl'
    })
    //渠道-渠道商管理-渠道商服务
    .state('main.channel_home.channel_service_list',{
        url:'/channel_service_list/:channel_id/:bs_id',
        templateUrl:'scripts/controllers/channel/channel_service_list.html?t='+v,
        controller:'ChannelServiceListCtrl'
    })
    //快麦订单信息
    .state('main.channel_home.quick_wheat_order',{
      url:'/quick_wheat_order',
      templateUrl:'scripts/controllers/channel/kuaimai/quick_wheat.html?t='+v,
      controller:'QuickWheatOrderCtrl'
    });
    
    /**
     * 合伙人
     */
    //主导航：合伙人
    $stateProvider.state('main.partner_home',{
        url:'/partner_home',
        templateUrl:'scripts/home/partner_home/partner_home.html?t='+v,
        controller:'PartnerHomeCtrl'
    })
    //合伙人-合伙人管理
    .state('main.partner_home.partner_manage',{
      url:'/partner_manage',
      templateUrl:'scripts/controllers/partner/partner_manage/partner_manage.html?t='+v,
      controller:'PartnerManageCtrl'
    })
    //合伙人-手动创建合伙人
    .state('main.partner_home.partner_add',{
      url:'/partner_add',
      templateUrl:'scripts/controllers/partner/partner_manage/addParter.html?t='+v,
      controller:'PartnerAddCtrl'
    })
    //合伙人-合伙人管理详情
    .state('main.partner_home.partner_manage_detail',{
      url:'/partner_manage_detail/:memberSn',
      templateUrl:'scripts/controllers/partner/partner_manage/partner_manage_detail.html?t='+v,
      controller:'PartnerDetailCtrl'
    })
    //合伙人-提现审核
    .state('main.partner_home.partner_cash',{
      url:'/partner_cash',
      templateUrl:'scripts/controllers/partner/partner_cash/partner_cash.html?t='+v,
      controller:'PartnerCashCtrl'
    })
    //合伙人-提现审核-提现详情
    .state('main.partner_home.partner_cash_detail',{
      url:'/partner_cash_detail/:id',
      templateUrl:'scripts/controllers/partner/partner_cash/partner_cash_detail.html?t='+v,
      controller:'PartnerCashDetailCtrl'
    })
    //合伙人-材料
    .state('main.partner_home.coupon_materials',{
      url:'/coupon_materials',
      templateUrl:'scripts/controllers/business/coupon/coupon_materials.html?t='+v,
      controller:'couponMaterialsCtrl'
    });

    //统计
    $stateProvider.state('main.statistics_home',{
        url: '/statistics_home',
        templateUrl: 'scripts/home/statistics_home/statistics_home.html?t='+v,
        controller: 'StatisticsCtrl'
    })
    .state('main.statistics_home.partner_list',{
        url: '/partner_list',
        templateUrl: 'scripts/controllers/statistics/partner/partner_list.html?t='+v,
        controller: 'PartnerListCtrl'
    })
    .state('main.statistics_home.businessStatistical_list',{
      url: '/businessStatistical_list',
      templateUrl: 'scripts/controllers/statistics/businessStatistical/businessStatistical_list.html?t='+v,
      controller: 'BusinessStatisticalListCtrl'
    });

    //主导航：珍珠-ipt
    $stateProvider.state('main.ipt_home',{
      url:'/ipt_home',
      templateUrl:'scripts/home/ipt_home/ipt_home.html?t='+v,
      controller:'IptHomeCtrl'
    })
    //珍珠-发放记录
    .state('main.ipt_home.record_list',{
      url:'/record_list',
      templateUrl:'scripts/controllers/ipt/record_list/record_list.html?t='+v,
      controller:'RecordListCtrl'
    })
    //珍珠-发放统计
    .state('main.ipt_home.record_statistics',{
      url:'/record_statistics',
      templateUrl:'scripts/controllers/ipt/record_statistics/record_statistics.html?t='+v,
      controller:'RecordStatisticsCtrl'
    })
    //珍珠-创力奖励记录
    .state('main.ipt_home.award_list',{
      url:'/award_list',
      templateUrl:'scripts/controllers/ipt/award_list/award_list.html?t='+v,
      controller:'AwardListCtrl'
    })
    //珍珠-创力奖励记录
    .state('main.ipt_home.pearl_list',{
      url:'/pearl_list',
      templateUrl:'scripts/controllers/ipt/pearl_list/pearl_list.html?t='+v,
      controller:'PearlListCtrl'
    });


    //主导航：维权
    $stateProvider.state('main.ip_protect_home',{
      url:'/ip_protect_home',
      templateUrl:'scripts/home/ip_protect_home/ip_protect_home.html?t='+v,
      controller:'IpProtectHomeCtrl'
    })
    //维权-电商侵权投诉-列表
    .state('main.ip_protect_home.ts_list',{
      url:'/ts_list',
      templateUrl:'scripts/controllers/ip_protect/ts_order/order_list.html?t='+v,
      controller:'TsListCtrl'
    })
    //维权-电商侵权投诉-详情
    .state('main.ip_protect_home.ts_detail',{
      url:'/ts_detail/:orderSn',
      templateUrl:'scripts/controllers/ip_protect/ts_order/order_detail.html?t='+v,
      controller:'TsOrderDetailCtrl'
    })
    //维权-保护投诉（官网）-列表
    .state('main.ip_protect_home.protect_list',{
      url:'/protect_list',
      templateUrl:'scripts/controllers/ip_protect/bh_order/order_list.html?t='+v,
      controller:'BhListCtrl'
    })
    //维权-保护投诉（官网）-详情
    .state('main.ip_protect_home.protect_detail',{
      url:'/protect_detail/:businessSn',
      templateUrl:'scripts/controllers/ip_protect/bh_order/order_detail.html?t='+v,
      controller:'BhOrderDetailCtrl'
    })
    //维权-电商维权申诉-列表
    .state('main.ip_protect_home.ss_list',{
      url:'/ss_list',
      templateUrl:'scripts/controllers/ip_protect/ss_order/order_list.html?t='+v,
      controller:'SsListCtrl'
    })
    //维权-电商维权申诉-详情
    .state('main.ip_protect_home.ss_detail',{
      url:'/ss_detail/:orderSn',
      templateUrl:'scripts/controllers/ip_protect/ss_order/order_detail.html?t='+v,
      controller:'SsOrderDetailCtrl'
    })
    //维权-网页侵权存证-列表
    .state('main.ip_protect_home.cz_list',{
      url:'/cz_list',
      templateUrl:'scripts/controllers/ip_protect/cz_order/order_list.html?t='+v,
      controller:'CzListCtrl'
    })
    //维权-网页侵权存证-详情
    .state('main.ip_protect_home.cz_detail',{
      url:'/cz_detail/:order_sn',
      templateUrl:'scripts/controllers/ip_protect/cz_order/order_detail.html?t='+v,
      controller:'CzOrderDetailCtrl'
    })
    //维权-专利侵权判定-列表
    .state('main.ip_protect_home.patent_list',{
      url:'/patent_list',
      templateUrl:'scripts/controllers/ip_protect/patent_order/order_list.html?t='+v,
      controller:'PatentListCtrl'
    })
    //维权-专利侵权判定-详情
    .state('main.ip_protect_home.patent_detail',{
      url:'/patent_detail/:orderSn',
      templateUrl:'scripts/controllers/ip_protect/patent_order/order_detail.html?t='+v,
      controller:'PatentOrderDetailCtrl'
    })
    //维权-质量抽检鉴定-列表
    .state('main.ip_protect_home.quality_list',{
      url:'/quality_list',
      templateUrl:'scripts/controllers/ip_protect/quality_order/order_list.html?t='+v,
      controller:'QualityListCtrl'
    })
    //维权-质量抽检鉴定-详情
    .state('main.ip_protect_home.quality_detail',{
      url:'/quality_detail/:orderSn',
      templateUrl:'scripts/controllers/ip_protect/quality_order/order_detail.html?t='+v,
      controller:'QualityOrderDetailCtrl'
    })
    //维权-海关资产保护-列表
    .state('main.ip_protect_home.customs_list',{
      url:'/customs_list',
      templateUrl:'scripts/controllers/ip_protect/customs_order/order_list.html?t='+v,
      controller:'CustomsListCtrl'
    })
    //维权-海关资产保护-详情
    .state('main.ip_protect_home.customs_detail',{
      url:'/customs_detail/:orderSn',
      templateUrl:'scripts/controllers/ip_protect/customs_order/order_detail.html?t='+v,
      controller:'CustomsOrderDetailCtrl'
    })
    //维权-维权公司案件-列表
    .state('main.ip_protect_home.case_list',{
      url:'/case_list',
      templateUrl:'scripts/controllers/ip_protect/case_order/order_list.html?t='+v,
      controller:'CaseListCtrl'
    })
    //维权-维权公司案件-详情
    .state('main.ip_protect_home.case_detail',{
      url:'/case_detail/:orderSn',
      templateUrl:'scripts/controllers/ip_protect/case_order/order_detail.html?t='+v,
      controller:'CaseOrderDetailCtrl'
    });


    //主导航：设置
    $stateProvider.state('main.setting_home',{
      url:'/setting_home',
      templateUrl:'scripts/home/setting_home/setting_home.html?t='+v,
      controller:'SettingHomeCtrl'
    })
    //设置-权限设置-管理员列表
    .state('main.setting_home.admin_list',{
      url:'/admin_list',
      templateUrl:'scripts/controllers/setting/admin/admin_list.html?t='+v,
      controller:'AdminListCtrl'
    })
    //设置-权限设置-添加管理员
    .state('main.setting_home.add_admin',{
      url:'/add_admin',
      templateUrl:'scripts/controllers/setting/admin/add_admin.html?t='+v,
      controller:'AddAdminCtrl'
    })
    //设置-权限设置-编辑管理员
    .state('main.setting_home.edit_admin',{
      url:'/edit_admin/:admin_id',
      templateUrl:'scripts/controllers/setting/admin/edit_admin.html?t='+v,
      controller:'EditAdminCtrl'
    })
    //设置-权限设置-功能组列表
    .state('main.setting_home.gadmin_list',{
      url:'/gadmin_list',
      templateUrl:'scripts/controllers/setting/g_limits/gadmin_list.html?t='+v,
      controller:'GAdminListCtrl'
    })
    //设置-权限设置-添加功能组
    .state('main.setting_home.add_gadmin',{
      url:'/add_gadmin',
      templateUrl:'scripts/controllers/setting/g_limits/add_gadmin.html?t='+v,
      controller:'AddGAdminCtrl'
    })
    //设置-权限设置-编辑功能组
    .state('main.setting_home.edit_gadmin',{
      url:'/edit_gadmin/:fg_id',
      templateUrl:'scripts/controllers/setting/g_limits/edit_gadmin.html?t='+v,
      controller:'EditGAdminCtrl'
    })
    //设置-权限设置-业务组列表
    .state('main.setting_home.data_group_list',{
      url:'/data_group_list',
      templateUrl:'scripts/controllers/setting/data/data_group_list.html?t='+v,
      controller:'DataGroupListCtrl'
    })
    //设置-权限设置-添加业务组
    .state('main.setting_home.add_data_group',{
      url:'/add_data_group',
      templateUrl:'scripts/controllers/setting/data/add_data_group.html?t='+v,
      controller:'AddDataGroupCtrl'
    })
    //设置-权限设置-编辑业务组
    .state('main.setting_home.edit_data_group',{
      url:'/edit_data_group/:dg_id',
      templateUrl:'scripts/controllers/setting/data/edit_data_group.html?t='+v,
      controller:'EditDataGroupCtrl'
    })
    //设置-操作日志
    .state('main.setting_home.log_list',{
      url:'/log_list',
      templateUrl:'scripts/controllers/setting/logs/log_list.html?t='+v,
      controller:'LogsCtrl'
    })
    //设置-消息通知
    .state('main.setting_home.news_list',{
      url:'/news_list',
      templateUrl:'scripts/controllers/setting/news/news_list.html?t='+v,
      controller:'NewsListCtrl'
    })
    //设置-订单分流
    .state('main.setting_home.OrderSetting',{
      url:'/OrderSetting',
      templateUrl:'scripts/controllers/setting/setOrder/OrderSetting.html?t='+v,
      controller:'OrderSettingCtrl'
    })
    //设置-支付方式
    .state('main.setting_home.payment_list',{
      url:'/payment_list',
      templateUrl:'scripts/controllers/setting/payment/payment_list.html?t='+v,
      controller:'PaymentListCtrl'
    })
    //设置-支付方式-添加支付方式
    .state('main.setting_home.add_payment',{
      url:'/add_payment',
      templateUrl:'scripts/controllers/setting/payment/add_payment.html?t='+v,
      controller:'AddPaymentCtrl'
    })
    //设置-支付方式-编辑支付方式ping++
    .state('main.setting_home.ping_edit',{
      url:'/ping_edit/:payment_id',
      templateUrl:'scripts/controllers/setting/payment/ping_edit.html?t='+v,
      controller:'PingPaymentEditCtrl'
    })
    //设置-支付方式-编辑支付方式
    .state('main.setting_home.payment_edit',{
      url:'/payment_edit/:payment_id',
      templateUrl:'scripts/controllers/setting/payment/payment_edit.html?t='+v,
      controller:'PaymentEditCtrl'
    })
    //设置-支付方式-编辑支付方式微信
    .state('main.setting_home.weChat_payment_edit',{
      url:'/weChat_payment_edit/:payment_id',
      templateUrl:'scripts/controllers/setting/payment/weChat_payment_edit.html?t='+v,
      controller:'WeChatPaymentEditCtrl'
    })
    //设置-物流公司
    .state('main.setting_home.express_list',{
      url:'/express_list',
      templateUrl:'scripts/controllers/setting/express/express_list.html?t='+v,
      controller:'ExpressCtrl'
    })
    //设置-邮件通知
    .state('main.setting_home.email',{
      url:'/email',
      templateUrl:'scripts/controllers/setting/email/email.html?t='+v,
      controller:'EmailCtrl'
    })
    //设置-邮件通知-邮件模板列表
    .state('main.setting_home.email_tpl',{
      url:'/email_tpl',
      templateUrl:'scripts/controllers/setting/email/email_tpl.html?t='+v,
      controller:'EmailTplCtrl'
    })
    //设置-邮件通知-邮件模板列表
    .state('main.setting_home.email_tpl_edit',{
      url:'/email_tpl_edit/:code',
      templateUrl:'scripts/controllers/setting/email/email_tpl_edit.html?t='+v,
      controller:'EmailTplEditCtrl'
    })
    //设置-邮件通知-添加邮件模板
    .state('main.setting_home.add_email_tpl',{
      url:'/add_email_tpl',
      templateUrl:'scripts/controllers/setting/email/add_email_tpl.html?t='+v,
      controller:'AddEmailTplCtrl'
    });


    /*默认打开欢迎页面*/
    $urlRouterProvider.otherwise('/login_page');
    $httpProvider.interceptors.push(["AuthenticationService",function(AuthenticationService) {
        return AuthenticationService.HttpResponseAuthHandlerMap;
    }]);
});
angular.module('iprpAdminApp').run(function($rootScope,$location,$http,$window,session,AuthenticationService,$templateCache,bsOrderService){
    $rootScope.safeApply = function(fn) {
        var phase = $rootScope.$$phase;
        if (phase === '$apply' || phase === '$digest') {
            if (fn && (typeof(fn) === 'function')) {
                fn();
            }
        } else {
            this.$apply(fn);
        }
    };
    
    AuthenticationService.$on('AccessForbidden',function(){
        $window.location.href = '#/main/left/error_page';
    });
    AuthenticationService.$on('NeedAuthentication',function(){
        $window.location.href = '#/login_page';
    });
    $rootScope.sessionService = session.initSession();
    $rootScope.$on("$stateChangeStart", function(event, toState, toParams, fromState, fromParams) {
        if (toState && toState.name == "login_page") {
            var random_bg = Math.floor(Math.random() * 5 + 1);
            var bg = 'url(styles/images/login/bg_' + random_bg + '.jpg)';
            $("body").css("background-image", bg);
        }
        /*if (toState && toState.templateUrl) {
          $templateCache.remove(toState.templateUrl);
        }*/
        var openFirstMenu = function(){
		    	if ($location.path().split('/').length >= 4) { return}
			    var els = $('.menutd .main-menu li').has('a').filter(function(index,item){
			    	return !$(item).hasClass('hide')
			    }).first().find('a').click();
		    }
		    setTimeout(openFirstMenu, 200);
    });
});
